USE [StudentDMC]
GO

/****** Object:  Table [dbo].[STUDENT_DETAILS]    Script Date: 11/3/2020 6:11:02 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[STUDENT_DETAILS](
	[REG_NUMBER] [varchar](25) NOT NULL,
	[NAME] [varchar](50) NOT NULL,
	[DEGREE] [varchar](50) NOT NULL,
 CONSTRAINT [PK_STUDENT_DETAILS] PRIMARY KEY CLUSTERED 
(
	[REG_NUMBER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


USE [StudentDMC]
GO

/****** Object:  Table [dbo].[COURSE_DETAILS]    Script Date: 11/3/2020 6:10:37 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[COURSE_DETAILS](
	[COURSE_ID] [varchar](50) NOT NULL,
	[COURSE_NAME] [varchar](50) NOT NULL,
	[CRDHRS] [int] NOT NULL,
	[SEMESTER] [int] NOT NULL,
	[MARKS] [bigint] NOT NULL,
	[FK_REG_NUM] [varchar](25) NOT NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[COURSE_DETAILS]  WITH CHECK ADD  CONSTRAINT [FK_REG_NUM] FOREIGN KEY([FK_REG_NUM])
REFERENCES [dbo].[STUDENT_DETAILS] ([REG_NUMBER])
GO

ALTER TABLE [dbo].[COURSE_DETAILS] CHECK CONSTRAINT [FK_REG_NUM]
GO



SELECT * FROM STUDENT_DETAILS
SELECT * FROM COURSE_DETAILS
DROP TABLE COURSE_DETAILS